apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-aut-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-aut
  template:
    metadata:
      labels:
        app: auth-aut
    spec:
      containers:
        - name: auth-aut-app
          image: auth-aut-app:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/auth_aut
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: auth-aut-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: auth-aut
  type: LoadBalancer